// /config/ApiConfig.kt
package com.example.customapp.config

// Import required packages to access API key from BuildConfig
import com.example.customapp.BuildConfig

// Configuration object for API settings: url, api key, headers and model settings
object ApiConfig {
    // Base URL for Perplexity API
    const val BASE_URL = "https://api.perplexity.ai/"
    // API key accessed from BuildConfig (generated by Secrets Gradle Plugin)
    val API_KEY: String
        get() = BuildConfig.PERPLEXITY_API_KEY
    // Headers
    const val HEADER_AUTHORIZATION = "Authorization"
    const val HEADER_CONTENT_TYPE = "Content-Type"
    const val CONTENT_TYPE_JSON = "application/json"
    // API endpoint for chat completions
    const val ENDPOINT_CHAT = "chat/completions"

    // Variables to set Model configuration (per Perplexity API documentation): https://docs.perplexity.ai/guides/search-quickstart

    // Controls model selection (SonarPro is more advanced but costs more)
    const val MODEL_SONAR = "sonar"
    const val MODEL_SONAR_PRO = "sonar-pro"
    // Controls randomness of the model's output (0 = deterministic, 1 = random)
    const val DEFAULT_TEMPERATURE = 0.2f
    // Controls the maximum number of tokens to generate in the response for efficient token usage
    const val DEFAULT_MAX_TOKENS = 1000
    // Controls content extraction from each webpage for efficiency (512 = concise, focused content)
    const val DEFAULT_MAX_TOKENS_PER_PAGE = 512
    // Limits number of search results to process
    const val DEFAULT_MAX_RESULTS = 5
    // Limits number of citations returned
    const val DEFAULT_NUM_SOURCES = 3
    // Limits the search domain to preset trusted sources (set by TrustedSources.kt)
    val DEFAULT_SEARCH_DOMAIN_FILTER: List<String>
        get() = TrustedSources.DOMAINS
}
