// ApiConfig.kt
package com.example.customapp.config

import com.example.customapp.BuildConfig


object ApiConfig {
    // Base URL for Perplexity API
    const val BASE_URL = "https://api.perplexity.ai/"

    // API key accessed from BuildConfig (generated by Secrets Gradle Plugin)
    val API_KEY: String
        get() = BuildConfig.PERPLEXITY_API_KEY

    // Headers
    const val HEADER_AUTHORIZATION = "Authorization"
    const val HEADER_CONTENT_TYPE = "Content-Type"
    const val CONTENT_TYPE_JSON = "application/json"

    // Endpoints
    const val ENDPOINT_CHAT = "chat/completions"

    // Model configuration
    const val MODEL_SONAR = "sonar"
    const val MODEL_SONAR_PRO = "sonar-pro"
    const val DEFAULT_TEMPERATURE = 0.2f
    const val DEFAULT_MAX_TOKENS = 1000
}

/**
 * Pre-defined trusted sources for fact-checking.
 * Used in search_domain_filter parameter to ensure
 * information comes from reliable sources only.
 */
object TrustedSources {
    val DOMAINS = listOf(
        // News organizations
        "reuters.com",
        "apnews.com",
        "npr.org",
        "bbc.com",
        "theguardian.com",

        // Encyclopedias
        "britannica.com",
        "wikipedia.org",

        // Fact-checkers
        "snopes.com",
        "factcheck.org",
        "politifact.com",

        // Government/Scientific
        "cdc.gov",
        "nasa.gov",
        "who.int"
    )
}
