// ApiConfig.kt
package com.example.customapp.config

import com.example.customapp.BuildConfig


object ApiConfig {
    // Base URL for Perplexity API
    const val BASE_URL = "https://api.perplexity.ai/"

    // API key accessed from BuildConfig (generated by Secrets Gradle Plugin)
    val API_KEY: String
        get() = BuildConfig.PERPLEXITY_API_KEY

    // Headers
    const val HEADER_AUTHORIZATION = "Authorization"
    const val HEADER_CONTENT_TYPE = "Content-Type"
    const val CONTENT_TYPE_JSON = "application/json"

    // Endpoints
    const val ENDPOINT_CHAT = "chat/completions"

    // Model configuration
    const val MODEL_SONAR = "sonar"
    const val MODEL_SONAR_PRO = "sonar-pro"
    const val DEFAULT_TEMPERATURE = 0.2f
    const val DEFAULT_MAX_TOKENS = 1000

    val DEFAULT_SEARCH_DOMAIN_FILTER: List<String>
        get() = TrustedSources.DOMAINS
}
